/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class CssInline */

#ifndef _Included_CssInline
#define _Included_CssInline
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     CssInline
 * Method:    inline
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_CssInline_inline
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
